apiVersion: v1
kind: Pod
metadata:
  name: layotto-pod-inject
  namespace: layotto-namespace
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
