apiVersion: v1
kind: Pod
metadata:
  name: layotto-pod
  namespace: layotto-namespace
  labels:
    # Add the following label to disable Layotto Sidecar injection for this pod
    mosn.io/sidecar-inject: "false"
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80